services:
  db:
    container_name: api_demo_db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - api-demo-network
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:

networks:
  api-demo-network:
    name: local-api-demo-network
